# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61868abc9ec8644ee829255c4f40611d06c3e82438a79f50be3cb9e6767944401118f0dbf74aaf13b320873b326e7aa5947d5de2db8e9cea4eb941783c3ee621

test:
  secret_key_base: a981b6de336fde263c308c2ced9cb4368c73d6a01063fae63a7b7c3f3c56d37ee9b02ef16544f153d912361fb0087e39c032f6d4a041b61258303d56f5d459d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
